//
//  StanBlockParser.swift
//  Stan
//
//  Slice B of Docs/Stan2AlistCommandPlan.md — a line/block parser for the
//  subset of Stan that `stancode` emits plus the idiomatic hand-written
//  shapes (radon_pp.stan). It splits the source into blocks, strips
//  comments, and parses `data` / `parameters` declarations and `model`
//  statements into a `StanProgram`.
//
//  `transformed data`, `transformed parameters`, `generated quantities`,
//  and `functions` are recognised and recorded in `droppedBlocks`
//  (Slice C warns), but their bodies are not interpreted.
//
//  The parser fails loud: any block we don't recognise, any declaration
//  or model statement we can't parse, throws `StanBlockParseError`
//  rather than silently dropping content. This keeps the "round-trip /
//  idiomatic-Stan only" contract honest.
//

import Foundation

enum StanBlockParser {

  /// Blocks whose contents we parse into the program.
  private static let translatedBlocks: Set<String> = ["data", "parameters", "model"]
  /// Blocks we recognise but deliberately skip (recorded as dropped).
  private static let skippedBlocks: [String] = [
    "transformed data",
    "transformed parameters",
    "generated quantities",
    "functions",
  ]

  static func parse(_ source: String) throws -> StanProgram {
    var program = StanProgram(dataDecls: [],
                              parameterDecls: [],
                              modelStatements: [],
                              droppedBlocks: [])
    // Strip comments up front so a leading/inter-block comment (e.g. the
    // generator's `// Generated by SwiftStan ulam port.` banner) doesn't
    // read as an unrecognized top-level construct.
    var rest = Substring(stripComments(source))

    while true {
      // Skip leading whitespace between blocks.
      rest = Substring(rest.drop { $0.isWhitespace })
      if rest.isEmpty { break }

      guard let (header, body, remainder) = try nextBlock(rest) else {
        throw StanBlockParseError.unrecognizedTopLevel(snippet(rest))
      }
      rest = remainder

      if translatedBlocks.contains(header) {
        switch header {
        case "data":
          program.dataDecls += try parseDeclarations(body)
        case "parameters":
          program.parameterDecls += try parseDeclarations(body)
        case "model":
          program.modelStatements += try parseModelStatements(body)
        default:
          break
        }
      } else {
        program.droppedBlocks.append(header)
      }
    }
    return program
  }

  // MARK: - Block splitting

  /// Read the next `header { body }` from the front of `source`. Returns
  /// the recognised header name, the brace body, and the remainder after
  /// the closing brace. Returns nil only when no recognised header
  /// matches (caller turns that into a fail-loud error).
  private static func nextBlock(
    _ source: Substring
  ) throws -> (header: String, body: String, remainder: Substring)? {
    guard let header = matchHeader(source) else { return nil }
    // Advance past the header to its opening brace.
    let afterHeader = source.dropFirst(header.count)
    guard let openRel = afterHeader.firstIndex(of: "{") else {
      throw StanBlockParseError.unterminatedBlock(header)
    }
    var depth = 0
    var idx = openRel
    while idx < afterHeader.endIndex {
      let c = afterHeader[idx]
      if c == "{" { depth += 1 }
      else if c == "}" {
        depth -= 1
        if depth == 0 {
          let bodyStart = afterHeader.index(after: openRel)
          let body = String(afterHeader[bodyStart..<idx])
          let remainder = afterHeader[afterHeader.index(after: idx)...]
          return (header, body, remainder)
        }
      }
      idx = afterHeader.index(after: idx)
    }
    throw StanBlockParseError.unterminatedBlock(header)
  }

  /// The recognised block header at the front of `source`, if any. Tries
  /// the two-word skipped headers before single-word ones so
  /// "transformed data" wins over a bare "data"-like prefix.
  private static func matchHeader(_ source: Substring) -> String? {
    let candidates = skippedBlocks + Array(translatedBlocks)
    // Longest first so "transformed parameters" beats "parameters".
    for header in candidates.sorted(by: { $0.count > $1.count }) {
      if matches(source, header: header) { return header }
    }
    return nil
  }

  /// True when `source` begins with `header` followed by whitespace or a
  /// brace — guards against "data" matching inside "database".
  private static func matches(_ source: Substring, header: String) -> Bool {
    // Normalise internal whitespace in the header ("transformed data"
    // may appear with multiple spaces / a newline between the words).
    let words = header.split(separator: " ")
    var cursor = source
    for (i, word) in words.enumerated() {
      cursor = Substring(cursor.drop { $0.isWhitespace })
      guard cursor.hasPrefix(word) else { return false }
      cursor = cursor.dropFirst(word.count)
      if i == words.count - 1 {
        // After the final word we need whitespace or the opening brace.
        guard let next = cursor.first else { return false }
        return next.isWhitespace || next == "{"
      }
    }
    return false
  }

  // MARK: - Declarations

  private static func parseDeclarations(_ body: String) throws -> [StanDecl] {
    let stripped = stripComments(body)
    let statements = splitStatements(stripped)
    return try statements.map(parseDeclaration)
  }

  private static func parseDeclaration(_ raw: String) throws -> StanDecl {
    let collapsed = collapseWhitespace(raw)
    guard let name = lastIdentifier(in: collapsed) else {
      throw StanBlockParseError.malformedDeclaration(raw)
    }
    // The spec is everything before the trailing name.
    guard let nameRange = collapsed.range(of: name, options: .backwards) else {
      throw StanBlockParseError.malformedDeclaration(raw)
    }
    var spec = String(collapsed[..<nameRange.lowerBound])
      .trimmingCharacters(in: .whitespaces)

    // Pull out a `<...>` constraint block, if present.
    var constraints = StanConstraints.none
    if let lt = spec.firstIndex(of: "<"),
       let gt = matchingAngle(spec, from: lt) {
      let inner = String(spec[spec.index(after: lt)..<gt])
      constraints = try parseConstraints(inner, raw: raw)
      spec.removeSubrange(lt...gt)
      spec = collapseWhitespace(spec).trimmingCharacters(in: .whitespaces)
    }

    let type = classifyType(spec)
    return StanDecl(name: name, type: type, constraints: constraints, raw: collapsed)
  }

  private static func classifyType(_ spec: String) -> StanType {
    let s = spec.trimmingCharacters(in: .whitespaces)
    if s.hasPrefix("array[") {
      let size = bracketContents(s, after: "array") ?? "N"
      if s.contains(" int") || s.hasSuffix("int") { return .arrayInt(size: size) }
      if s.contains(" real") || s.hasSuffix("real") { return .arrayReal(size: size) }
      return .other(s)
    }
    if s.hasPrefix("vector") {
      if let size = bracketContents(s, after: "vector") { return .vector(size: size) }
      return .other(s)
    }
    if s == "real" { return .real }
    if s == "int" { return .int }
    return .other(s)
  }

  private static func parseConstraints(_ inner: String, raw: String) throws -> StanConstraints {
    var c = StanConstraints.none
    for pair in splitTopLevelCommas(inner) {
      let kv = pair.split(separator: "=", maxSplits: 1).map {
        $0.trimmingCharacters(in: .whitespaces)
      }
      guard kv.count == 2 else {
        throw StanBlockParseError.malformedDeclaration(raw)
      }
      switch kv[0] {
      case "lower":      c.lower = kv[1]
      case "upper":      c.upper = kv[1]
      case "offset":     c.offset = kv[1]
      case "multiplier": c.multiplier = kv[1]
      default:
        throw StanBlockParseError.malformedDeclaration(raw)
      }
    }
    return c
  }

  // MARK: - Model statements

  private static func parseModelStatements(_ body: String) throws -> [StanModelStatement] {
    let stripped = stripComments(body)
    // The statement splitter is `;`-based and can't span a `for`/`while`
    // loop body. The forward emitter produces a loop only for a
    // non-vectorisable indexed linear model (e.g. a `vector * vector`
    // term). Fail loud rather than mis-parse the `{ … }` block.
    if stripped.range(of: #"\b(for|while)\b"#, options: .regularExpression) != nil
        || stripped.contains("{") {
      throw StanBlockParseError.unsupportedLoop
    }
    let statements = splitStatements(stripped)
    return try statements.compactMap(parseModelStatement)
  }

  /// Stan type keywords that begin a model-block local declaration
  /// (e.g. `vector[N] p;` — the generator declares derived linear
  /// predictors before assigning them). Such declarations carry no
  /// statement meaning for the reverse and are skipped.
  private static let typeKeywords: Set<String> = [
    "vector", "row_vector", "matrix", "real", "int", "array", "simplex",
    "ordered", "positive_ordered", "unit_vector", "cov_matrix",
    "corr_matrix", "cholesky_factor_corr", "cholesky_factor_cov",
  ]

  private static func parseModelStatement(_ raw: String) throws -> StanModelStatement? {
    let s = collapseWhitespace(raw).trimmingCharacters(in: .whitespaces)
    if let tildeRange = s.range(of: "~") {
      let lhs = String(s[..<tildeRange.lowerBound]).trimmingCharacters(in: .whitespaces)
      let rhs = String(s[tildeRange.upperBound...]).trimmingCharacters(in: .whitespaces)
      return try parseSampling(lhs: lhs, rhs: rhs, raw: raw)
    }
    if let eqRange = s.range(of: "=") {
      let lhs = String(s[..<eqRange.lowerBound]).trimmingCharacters(in: .whitespaces)
      let rhs = String(s[eqRange.upperBound...]).trimmingCharacters(in: .whitespaces)
      guard !lhs.isEmpty, !rhs.isEmpty else {
        throw StanBlockParseError.malformedModelStatement(raw)
      }
      return .assignment(lhs: lhs, rhs: rhs)
    }
    // No `~` or `=`: a bare local declaration (`vector[N] p`) — skip it.
    if let firstWord = s.split(whereSeparator: { $0 == " " || $0 == "[" }).first,
       typeKeywords.contains(String(firstWord)) {
      return nil
    }
    throw StanBlockParseError.malformedModelStatement(raw)
  }

  private static func parseSampling(lhs: String,
                                    rhs: String,
                                    raw: String) throws -> StanModelStatement {
    guard !lhs.isEmpty,
          let openParen = rhs.firstIndex(of: "(") else {
      throw StanBlockParseError.malformedModelStatement(raw)
    }
    let distName = String(rhs[..<openParen]).trimmingCharacters(in: .whitespaces)
    guard !distName.isEmpty,
          let closeParen = matchingParen(rhs, from: openParen) else {
      throw StanBlockParseError.malformedModelStatement(raw)
    }
    let argsInner = String(rhs[rhs.index(after: openParen)..<closeParen])
    let args = splitTopLevelCommas(argsInner)
      .map { $0.trimmingCharacters(in: .whitespaces) }
      .filter { !$0.isEmpty }

    // Anything after the `)` must be a `T[...]` truncation suffix.
    let tail = String(rhs[rhs.index(after: closeParen)...])
      .trimmingCharacters(in: .whitespaces)
    var truncation: StanTruncation? = nil
    if !tail.isEmpty {
      guard tail.hasPrefix("T["), tail.hasSuffix("]") else {
        throw StanBlockParseError.malformedModelStatement(raw)
      }
      let inner = String(tail.dropFirst(2).dropLast())
      let parts = splitTopLevelCommas(inner).map {
        $0.trimmingCharacters(in: .whitespaces)
      }
      let lower = parts.indices.contains(0) && !parts[0].isEmpty ? parts[0] : nil
      let upper = parts.indices.contains(1) && !parts[1].isEmpty ? parts[1] : nil
      truncation = StanTruncation(lower: lower, upper: upper)
    }
    return .sampling(lhs: lhs, distName: distName, args: args, truncation: truncation)
  }

  // MARK: - Lexical helpers

  /// Remove `//` line comments and `/* ... */` block comments.
  private static func stripComments(_ s: String) -> String {
    var out = ""
    let chars = Array(s)
    var i = 0
    while i < chars.count {
      if chars[i] == "/", i + 1 < chars.count, chars[i + 1] == "/" {
        while i < chars.count, chars[i] != "\n" { i += 1 }
      } else if chars[i] == "/", i + 1 < chars.count, chars[i + 1] == "*" {
        i += 2
        while i + 1 < chars.count, !(chars[i] == "*" && chars[i + 1] == "/") { i += 1 }
        i += 2
      } else {
        out.append(chars[i])
        i += 1
      }
    }
    return out
  }

  /// Split a block body into individual `;`-terminated statements,
  /// trimming and dropping empties.
  private static func splitStatements(_ s: String) -> [String] {
    s.components(separatedBy: ";")
      .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
      .filter { !$0.isEmpty }
  }

  private static func collapseWhitespace(_ s: String) -> String {
    s.replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
  }

  private static func lastIdentifier(in declaration: String) -> String? {
    let chars = Array(declaration.trimmingCharacters(in: .whitespaces))
    guard !chars.isEmpty else { return nil }
    var end = chars.count
    while end > 0, !isIdentifierChar(chars[end - 1]) { end -= 1 }
    var start = end
    while start > 0, isIdentifierChar(chars[start - 1]) { start -= 1 }
    guard start < end else { return nil }
    return String(chars[start..<end])
  }

  private static func isIdentifierChar(_ c: Character) -> Bool {
    c.isLetter || c.isNumber || c == "_"
  }

  /// Contents of the `[...]` immediately following `prefix` in `spec`,
  /// e.g. `bracketContents("array[N] int", after: "array")` → "N".
  private static func bracketContents(_ spec: String, after prefix: String) -> String? {
    guard let prefixRange = spec.range(of: prefix) else { return nil }
    let afterPrefix = spec[prefixRange.upperBound...]
    guard let open = afterPrefix.firstIndex(of: "["),
          let close = afterPrefix.firstIndex(of: "]"),
          open < close else { return nil }
    return String(afterPrefix[afterPrefix.index(after: open)..<close])
      .trimmingCharacters(in: .whitespaces)
  }

  private static func matchingParen(_ s: String, from open: String.Index) -> String.Index? {
    matchingDelimiter(s, from: open, open: "(", close: ")")
  }

  private static func matchingAngle(_ s: String, from open: String.Index) -> String.Index? {
    matchingDelimiter(s, from: open, open: "<", close: ">")
  }

  private static func matchingDelimiter(_ s: String,
                                        from open: String.Index,
                                        open openChar: Character,
                                        close closeChar: Character) -> String.Index? {
    var depth = 0
    var idx = open
    while idx < s.endIndex {
      let c = s[idx]
      if c == openChar { depth += 1 }
      else if c == closeChar {
        depth -= 1
        if depth == 0 { return idx }
      }
      idx = s.index(after: idx)
    }
    return nil
  }

  /// Split on commas that sit at bracket/paren depth 0, so
  /// `alpha[county] + beta*floor, sigma` → ["alpha[county] + beta*floor", "sigma"].
  private static func splitTopLevelCommas(_ s: String) -> [String] {
    var parts: [String] = []
    var current = ""
    var depth = 0
    for c in s {
      switch c {
      case "(", "[", "<": depth += 1; current.append(c)
      case ")", "]", ">": depth -= 1; current.append(c)
      case "," where depth == 0:
        parts.append(current)
        current = ""
      default:
        current.append(c)
      }
    }
    if !current.trimmingCharacters(in: .whitespaces).isEmpty || !parts.isEmpty {
      parts.append(current)
    }
    return parts
  }

  private static func snippet(_ s: Substring) -> String {
    String(s.prefix(40)).trimmingCharacters(in: .whitespacesAndNewlines)
  }
}
